// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package gwxdsapi defines the neutral xDS transfer schema for Gateway API
// resources. Istiod serialises resolved listeners and routes into these
// messages and distributes them via xDS to any gwxds-capable proxy.
// The schema is intentionally self-contained: it imports no other istio
// protos and carries no proxy-specific logic.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gwxdsapi/gwxds.proto

package gwxdsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol identifies the listener protocol.
type Protocol int32

const (
	Protocol_UNKNOWN Protocol = 0
	Protocol_HTTP    Protocol = 1
	Protocol_HTTPS   Protocol = 2
	Protocol_TLS     Protocol = 3
	Protocol_TCP     Protocol = 4
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "UNKNOWN",
		1: "HTTP",
		2: "HTTPS",
		3: "TLS",
		4: "TCP",
	}
	Protocol_value = map[string]int32{
		"UNKNOWN": 0,
		"HTTP":    1,
		"HTTPS":   2,
		"TLS":     3,
		"TCP":     4,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_gwxdsapi_gwxds_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_gwxdsapi_gwxds_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{0}
}

// FailureMode controls proxy behaviour when an InferencePool endpoint picker
// is unreachable.
type FailureMode int32

const (
	// FAIL_CLOSED rejects the request when the endpoint picker is unreachable.
	FailureMode_FAIL_CLOSED FailureMode = 0
	// FAIL_OPEN falls back to direct routing when the endpoint picker is unreachable.
	FailureMode_FAIL_OPEN FailureMode = 1
)

// Enum value maps for FailureMode.
var (
	FailureMode_name = map[int32]string{
		0: "FAIL_CLOSED",
		1: "FAIL_OPEN",
	}
	FailureMode_value = map[string]int32{
		"FAIL_CLOSED": 0,
		"FAIL_OPEN":   1,
	}
)

func (x FailureMode) Enum() *FailureMode {
	p := new(FailureMode)
	*p = x
	return p
}

func (x FailureMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gwxdsapi_gwxds_proto_enumTypes[1].Descriptor()
}

func (FailureMode) Type() protoreflect.EnumType {
	return &file_gwxdsapi_gwxds_proto_enumTypes[1]
}

func (x FailureMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureMode.Descriptor instead.
func (FailureMode) EnumDescriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{1}
}

// TLSConfig holds resolved TLS material for a listener.
// Certificate and key bytes are resolved by istiod; the proxy does not need
// Kubernetes API access.
type TLSConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded certificate chain.
	CertPem []byte `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	// PEM-encoded private key.
	KeyPem []byte `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	// PEM-encoded CA certificate for client verification (mTLS).
	// Empty when mutual TLS is not required.
	CaPem []byte `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// Minimum TLS version string, e.g. "TLSv1_2".
	MinVersion    string `protobuf:"bytes,4,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSConfig) Reset() {
	*x = TLSConfig{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfig) ProtoMessage() {}

func (x *TLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConfig.ProtoReflect.Descriptor instead.
func (*TLSConfig) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{0}
}

func (x *TLSConfig) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *TLSConfig) GetKeyPem() []byte {
	if x != nil {
		return x.KeyPem
	}
	return nil
}

func (x *TLSConfig) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *TLSConfig) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

// Listener is a resolved Gateway listener ready for xDS distribution.
type Listener struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable key of the form "namespace/gateway-name/listener-name".
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// SNI / virtual-host hostname pattern (may contain wildcards).
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Listener port.
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Listener protocol.
	Protocol Protocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=istio.gwxds.Protocol" json:"protocol,omitempty"`
	// Resolved TLS material. Absent for plain-text listeners.
	Tls *TLSConfig `protobuf:"bytes,5,opt,name=tls,proto3" json:"tls,omitempty"`
	// Set of "group/kind" strings identifying route kinds allowed to attach.
	AllowedRoutes []string `protobuf:"bytes,6,rep,name=allowed_routes,json=allowedRoutes,proto3" json:"allowed_routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listener) Reset() {
	*x = Listener{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{1}
}

func (x *Listener) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Listener) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Listener) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Listener) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_UNKNOWN
}

func (x *Listener) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Listener) GetAllowedRoutes() []string {
	if x != nil {
		return x.AllowedRoutes
	}
	return nil
}

// BackendRef is a lightweight host:port reference used within backend descriptors.
type BackendRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendRef) Reset() {
	*x = BackendRef{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendRef) ProtoMessage() {}

func (x *BackendRef) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendRef.ProtoReflect.Descriptor instead.
func (*BackendRef) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{2}
}

func (x *BackendRef) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BackendRef) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// InferencePool describes the endpoint picker configuration for an InferencePool
// backend. Proxies that implement the EPP protocol delegate per-request endpoint
// selection to the picker. Proxies without EPP support should warn and may fall
// back to direct routing or reject the request per failure_mode.
type InferencePool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EPP sidecar that selects the actual backend pod per request.
	EndpointPicker *BackendRef `protobuf:"bytes,1,opt,name=endpoint_picker,json=endpointPicker,proto3" json:"endpoint_picker,omitempty"`
	// Controls behaviour when the endpoint picker is unreachable.
	FailureMode   FailureMode `protobuf:"varint,2,opt,name=failure_mode,json=failureMode,proto3,enum=istio.gwxds.FailureMode" json:"failure_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferencePool) Reset() {
	*x = InferencePool{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferencePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferencePool) ProtoMessage() {}

func (x *InferencePool) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferencePool.ProtoReflect.Descriptor instead.
func (*InferencePool) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{3}
}

func (x *InferencePool) GetEndpointPicker() *BackendRef {
	if x != nil {
		return x.EndpointPicker
	}
	return nil
}

func (x *InferencePool) GetFailureMode() FailureMode {
	if x != nil {
		return x.FailureMode
	}
	return FailureMode_FAIL_CLOSED
}

// BackendTLS carries the resolved TLS policy for a single backend.
// Absent means no TLS policy applies (plaintext connection to backend).
type BackendTLS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded CA bundle for verifying the backend certificate.
	// Empty means use the system CA trust store.
	CaCert []byte `protobuf:"bytes,1,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	// Expected TLS SNI / server name.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Expected Subject Alternative Names.
	Sans []string `protobuf:"bytes,3,rep,name=sans,proto3" json:"sans,omitempty"`
	// PEM-encoded client certificate for mTLS to the backend.
	ClientCert []byte `protobuf:"bytes,4,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	// PEM-encoded client private key for mTLS to the backend.
	ClientKey []byte `protobuf:"bytes,5,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	// Set when the policy referenced a certificate that could not be resolved.
	// Proxies should treat this as a hard error.
	Invalid       bool `protobuf:"varint,6,opt,name=invalid,proto3" json:"invalid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendTLS) Reset() {
	*x = BackendTLS{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendTLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendTLS) ProtoMessage() {}

func (x *BackendTLS) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendTLS.ProtoReflect.Descriptor instead.
func (*BackendTLS) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{4}
}

func (x *BackendTLS) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *BackendTLS) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *BackendTLS) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *BackendTLS) GetClientCert() []byte {
	if x != nil {
		return x.ClientCert
	}
	return nil
}

func (x *BackendTLS) GetClientKey() []byte {
	if x != nil {
		return x.ClientKey
	}
	return nil
}

func (x *BackendTLS) GetInvalid() bool {
	if x != nil {
		return x.Invalid
	}
	return false
}

// Backend is a resolved upstream target.
type Backend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FQDN of the backend service.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Backend service port.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Traffic weight for weighted routing. 0 is treated as 1.
	Weight uint32 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// Set when this backend is an InferencePool.
	InferencePool *InferencePool `protobuf:"bytes,4,opt,name=inference_pool,json=inferencePool,proto3" json:"inference_pool,omitempty"`
	// Set when a BackendTLSPolicy applies to this backend.
	Tls *BackendTLS `protobuf:"bytes,5,opt,name=tls,proto3" json:"tls,omitempty"`
	// Pod/target port to open upstream connections to when it differs from port (Kubernetes targetPort).
	DialPort      uint32 `protobuf:"varint,6,opt,name=dial_port,json=dialPort,proto3" json:"dial_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{5}
}

func (x *Backend) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Backend) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Backend) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Backend) GetInferencePool() *InferencePool {
	if x != nil {
		return x.InferencePool
	}
	return nil
}

func (x *Backend) GetTls() *BackendTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Backend) GetDialPort() uint32 {
	if x != nil {
		return x.DialPort
	}
	return 0
}

// RequestRedirect mirrors Gateway API HTTPRequestRedirect for redirect-only rules.
type RequestRedirect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Scheme        string                 `protobuf:"bytes,4,opt,name=scheme,proto3" json:"scheme,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRedirect) Reset() {
	*x = RequestRedirect{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRedirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRedirect) ProtoMessage() {}

func (x *RequestRedirect) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRedirect.ProtoReflect.Descriptor instead.
func (*RequestRedirect) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{6}
}

func (x *RequestRedirect) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RequestRedirect) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestRedirect) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RequestRedirect) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *RequestRedirect) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

// Named header value (Gateway HTTPHeader).
type HeaderNameValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderNameValue) Reset() {
	*x = HeaderNameValue{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderNameValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderNameValue) ProtoMessage() {}

func (x *HeaderNameValue) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderNameValue.ProtoReflect.Descriptor instead.
func (*HeaderNameValue) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{7}
}

func (x *HeaderNameValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeaderNameValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// RequestHeaderModifier mirrors Gateway API HTTPHeaderFilter for request rules.
type RequestHeaderModifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           []*HeaderNameValue     `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty"`
	Add           []*HeaderNameValue     `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeaderModifier) Reset() {
	*x = RequestHeaderModifier{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeaderModifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeaderModifier) ProtoMessage() {}

func (x *RequestHeaderModifier) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeaderModifier.ProtoReflect.Descriptor instead.
func (*RequestHeaderModifier) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{8}
}

func (x *RequestHeaderModifier) GetSet() []*HeaderNameValue {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *RequestHeaderModifier) GetAdd() []*HeaderNameValue {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *RequestHeaderModifier) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

// RouteMatch describes matching criteria for a single route rule.
type RouteMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP path prefix match. Empty means match all paths.
	PathPrefix string `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// Exact path match. Takes priority over path_prefix when set.
	PathExact string `protobuf:"bytes,2,opt,name=path_exact,json=pathExact,proto3" json:"path_exact,omitempty"`
	// Regex path match.
	PathRegex string `protobuf:"bytes,3,opt,name=path_regex,json=pathRegex,proto3" json:"path_regex,omitempty"`
	// Required header key/value matches.
	Headers map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// HTTP methods to match. Empty means all methods.
	Methods       []string `protobuf:"bytes,5,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteMatch) Reset() {
	*x = RouteMatch{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteMatch) ProtoMessage() {}

func (x *RouteMatch) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteMatch.ProtoReflect.Descriptor instead.
func (*RouteMatch) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{9}
}

func (x *RouteMatch) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *RouteMatch) GetPathExact() string {
	if x != nil {
		return x.PathExact
	}
	return ""
}

func (x *RouteMatch) GetPathRegex() string {
	if x != nil {
		return x.PathRegex
	}
	return ""
}

func (x *RouteMatch) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RouteMatch) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

// Route is a resolved route rule attached to a listener.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable key of the form "namespace/route-name/rule-index".
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Key of the Listener this route is attached to.
	ListenerKey string `protobuf:"bytes,2,opt,name=listener_key,json=listenerKey,proto3" json:"listener_key,omitempty"`
	// Virtual-host hostnames this route serves.
	Hostnames []string `protobuf:"bytes,3,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	// Matching criteria. Empty means match all requests.
	Matches []*RouteMatch `protobuf:"bytes,4,rep,name=matches,proto3" json:"matches,omitempty"`
	// Upstream targets for matched requests.
	Backends []*Backend `protobuf:"bytes,5,rep,name=backends,proto3" json:"backends,omitempty"`
	// When set, matched requests are redirected (Gateway RequestRedirect filter).
	RequestRedirect *RequestRedirect `protobuf:"bytes,6,opt,name=request_redirect,json=requestRedirect,proto3" json:"request_redirect,omitempty"`
	// Per-route request header changes (Gateway RequestHeaderModifier). Applied after match.
	RequestHeaderModifier *RequestHeaderModifier `protobuf:"bytes,7,opt,name=request_header_modifier,json=requestHeaderModifier,proto3" json:"request_header_modifier,omitempty"`
	// When true, the rule matched but backend refs did not resolve — respond with HTTP 500.
	InvalidBackendRef bool `protobuf:"varint,8,opt,name=invalid_backend_ref,json=invalidBackendRef,proto3" json:"invalid_backend_ref,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{10}
}

func (x *Route) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Route) GetListenerKey() string {
	if x != nil {
		return x.ListenerKey
	}
	return ""
}

func (x *Route) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

func (x *Route) GetMatches() []*RouteMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *Route) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *Route) GetRequestRedirect() *RequestRedirect {
	if x != nil {
		return x.RequestRedirect
	}
	return nil
}

func (x *Route) GetRequestHeaderModifier() *RequestHeaderModifier {
	if x != nil {
		return x.RequestHeaderModifier
	}
	return nil
}

func (x *Route) GetInvalidBackendRef() bool {
	if x != nil {
		return x.InvalidBackendRef
	}
	return false
}

// Resource is the top-level xDS resource served to a gwxds-capable proxy.
// It bundles a resolved listener with all its attached routes.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Same as the contained listener's key.
	Key           string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Listener      *Listener `protobuf:"bytes,2,opt,name=listener,proto3" json:"listener,omitempty"`
	Routes        []*Route  `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_gwxdsapi_gwxds_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_gwxdsapi_gwxds_proto_rawDescGZIP(), []int{11}
}

func (x *Resource) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Resource) GetListener() *Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

func (x *Resource) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_gwxdsapi_gwxds_proto protoreflect.FileDescriptor

const file_gwxdsapi_gwxds_proto_rawDesc = "" +
	"\n" +
	"\x14gwxdsapi/gwxds.proto\x12\vistio.gwxds\"w\n" +
	"\tTLSConfig\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\fR\x06keyPem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\fR\x05caPem\x12\x1f\n" +
	"\vmin_version\x18\x04 \x01(\tR\n" +
	"minVersion\"\xd0\x01\n" +
	"\bListener\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x121\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x15.istio.gwxds.ProtocolR\bprotocol\x12(\n" +
	"\x03tls\x18\x05 \x01(\v2\x16.istio.gwxds.TLSConfigR\x03tls\x12%\n" +
	"\x0eallowed_routes\x18\x06 \x03(\tR\rallowedRoutes\"4\n" +
	"\n" +
	"BackendRef\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x8e\x01\n" +
	"\rInferencePool\x12@\n" +
	"\x0fendpoint_picker\x18\x01 \x01(\v2\x17.istio.gwxds.BackendRefR\x0eendpointPicker\x12;\n" +
	"\ffailure_mode\x18\x02 \x01(\x0e2\x18.istio.gwxds.FailureModeR\vfailureMode\"\xaf\x01\n" +
	"\n" +
	"BackendTLS\x12\x17\n" +
	"\aca_cert\x18\x01 \x01(\fR\x06caCert\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04sans\x18\x03 \x03(\tR\x04sans\x12\x1f\n" +
	"\vclient_cert\x18\x04 \x01(\fR\n" +
	"clientCert\x12\x1d\n" +
	"\n" +
	"client_key\x18\x05 \x01(\fR\tclientKey\x12\x18\n" +
	"\ainvalid\x18\x06 \x01(\bR\ainvalid\"\xd4\x01\n" +
	"\aBackend\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\x12A\n" +
	"\x0einference_pool\x18\x04 \x01(\v2\x1a.istio.gwxds.InferencePoolR\rinferencePool\x12)\n" +
	"\x03tls\x18\x05 \x01(\v2\x17.istio.gwxds.BackendTLSR\x03tls\x12\x1b\n" +
	"\tdial_port\x18\x06 \x01(\rR\bdialPort\"\x8e\x01\n" +
	"\x0fRequestRedirect\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x16\n" +
	"\x06scheme\x18\x04 \x01(\tR\x06scheme\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\rR\n" +
	"statusCode\";\n" +
	"\x0fHeaderNameValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8f\x01\n" +
	"\x15RequestHeaderModifier\x12.\n" +
	"\x03set\x18\x01 \x03(\v2\x1c.istio.gwxds.HeaderNameValueR\x03set\x12.\n" +
	"\x03add\x18\x02 \x03(\v2\x1c.istio.gwxds.HeaderNameValueR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"\x81\x02\n" +
	"\n" +
	"RouteMatch\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12\x1d\n" +
	"\n" +
	"path_exact\x18\x02 \x01(\tR\tpathExact\x12\x1d\n" +
	"\n" +
	"path_regex\x18\x03 \x01(\tR\tpathRegex\x12>\n" +
	"\aheaders\x18\x04 \x03(\v2$.istio.gwxds.RouteMatch.HeadersEntryR\aheaders\x12\x18\n" +
	"\amethods\x18\x05 \x03(\tR\amethods\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x03\n" +
	"\x05Route\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\flistener_key\x18\x02 \x01(\tR\vlistenerKey\x12\x1c\n" +
	"\thostnames\x18\x03 \x03(\tR\thostnames\x121\n" +
	"\amatches\x18\x04 \x03(\v2\x17.istio.gwxds.RouteMatchR\amatches\x120\n" +
	"\bbackends\x18\x05 \x03(\v2\x14.istio.gwxds.BackendR\bbackends\x12G\n" +
	"\x10request_redirect\x18\x06 \x01(\v2\x1c.istio.gwxds.RequestRedirectR\x0frequestRedirect\x12Z\n" +
	"\x17request_header_modifier\x18\a \x01(\v2\".istio.gwxds.RequestHeaderModifierR\x15requestHeaderModifier\x12.\n" +
	"\x13invalid_backend_ref\x18\b \x01(\bR\x11invalidBackendRef\"{\n" +
	"\bResource\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\blistener\x18\x02 \x01(\v2\x15.istio.gwxds.ListenerR\blistener\x12*\n" +
	"\x06routes\x18\x03 \x03(\v2\x12.istio.gwxds.RouteR\x06routes*>\n" +
	"\bProtocol\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\t\n" +
	"\x05HTTPS\x10\x02\x12\a\n" +
	"\x03TLS\x10\x03\x12\a\n" +
	"\x03TCP\x10\x04*-\n" +
	"\vFailureMode\x12\x0f\n" +
	"\vFAIL_CLOSED\x10\x00\x12\r\n" +
	"\tFAIL_OPEN\x10\x01B\x1dZ\x1bistio.io/istio/pkg/gwxdsapib\x06proto3"

var (
	file_gwxdsapi_gwxds_proto_rawDescOnce sync.Once
	file_gwxdsapi_gwxds_proto_rawDescData []byte
)

func file_gwxdsapi_gwxds_proto_rawDescGZIP() []byte {
	file_gwxdsapi_gwxds_proto_rawDescOnce.Do(func() {
		file_gwxdsapi_gwxds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gwxdsapi_gwxds_proto_rawDesc), len(file_gwxdsapi_gwxds_proto_rawDesc)))
	})
	return file_gwxdsapi_gwxds_proto_rawDescData
}

var file_gwxdsapi_gwxds_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gwxdsapi_gwxds_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gwxdsapi_gwxds_proto_goTypes = []any{
	(Protocol)(0),                 // 0: istio.gwxds.Protocol
	(FailureMode)(0),              // 1: istio.gwxds.FailureMode
	(*TLSConfig)(nil),             // 2: istio.gwxds.TLSConfig
	(*Listener)(nil),              // 3: istio.gwxds.Listener
	(*BackendRef)(nil),            // 4: istio.gwxds.BackendRef
	(*InferencePool)(nil),         // 5: istio.gwxds.InferencePool
	(*BackendTLS)(nil),            // 6: istio.gwxds.BackendTLS
	(*Backend)(nil),               // 7: istio.gwxds.Backend
	(*RequestRedirect)(nil),       // 8: istio.gwxds.RequestRedirect
	(*HeaderNameValue)(nil),       // 9: istio.gwxds.HeaderNameValue
	(*RequestHeaderModifier)(nil), // 10: istio.gwxds.RequestHeaderModifier
	(*RouteMatch)(nil),            // 11: istio.gwxds.RouteMatch
	(*Route)(nil),                 // 12: istio.gwxds.Route
	(*Resource)(nil),              // 13: istio.gwxds.Resource
	nil,                           // 14: istio.gwxds.RouteMatch.HeadersEntry
}
var file_gwxdsapi_gwxds_proto_depIdxs = []int32{
	0,  // 0: istio.gwxds.Listener.protocol:type_name -> istio.gwxds.Protocol
	2,  // 1: istio.gwxds.Listener.tls:type_name -> istio.gwxds.TLSConfig
	4,  // 2: istio.gwxds.InferencePool.endpoint_picker:type_name -> istio.gwxds.BackendRef
	1,  // 3: istio.gwxds.InferencePool.failure_mode:type_name -> istio.gwxds.FailureMode
	5,  // 4: istio.gwxds.Backend.inference_pool:type_name -> istio.gwxds.InferencePool
	6,  // 5: istio.gwxds.Backend.tls:type_name -> istio.gwxds.BackendTLS
	9,  // 6: istio.gwxds.RequestHeaderModifier.set:type_name -> istio.gwxds.HeaderNameValue
	9,  // 7: istio.gwxds.RequestHeaderModifier.add:type_name -> istio.gwxds.HeaderNameValue
	14, // 8: istio.gwxds.RouteMatch.headers:type_name -> istio.gwxds.RouteMatch.HeadersEntry
	11, // 9: istio.gwxds.Route.matches:type_name -> istio.gwxds.RouteMatch
	7,  // 10: istio.gwxds.Route.backends:type_name -> istio.gwxds.Backend
	8,  // 11: istio.gwxds.Route.request_redirect:type_name -> istio.gwxds.RequestRedirect
	10, // 12: istio.gwxds.Route.request_header_modifier:type_name -> istio.gwxds.RequestHeaderModifier
	3,  // 13: istio.gwxds.Resource.listener:type_name -> istio.gwxds.Listener
	12, // 14: istio.gwxds.Resource.routes:type_name -> istio.gwxds.Route
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gwxdsapi_gwxds_proto_init() }
func file_gwxdsapi_gwxds_proto_init() {
	if File_gwxdsapi_gwxds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gwxdsapi_gwxds_proto_rawDesc), len(file_gwxdsapi_gwxds_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gwxdsapi_gwxds_proto_goTypes,
		DependencyIndexes: file_gwxdsapi_gwxds_proto_depIdxs,
		EnumInfos:         file_gwxdsapi_gwxds_proto_enumTypes,
		MessageInfos:      file_gwxdsapi_gwxds_proto_msgTypes,
	}.Build()
	File_gwxdsapi_gwxds_proto = out.File
	file_gwxdsapi_gwxds_proto_goTypes = nil
	file_gwxdsapi_gwxds_proto_depIdxs = nil
}
