// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package gwxdsapi

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for TLSConfig
func (this *TLSConfig) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TLSConfig
func (this *TLSConfig) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Listener
func (this *Listener) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Listener
func (this *Listener) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BackendRef
func (this *BackendRef) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BackendRef
func (this *BackendRef) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for InferencePool
func (this *InferencePool) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for InferencePool
func (this *InferencePool) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BackendTLS
func (this *BackendTLS) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BackendTLS
func (this *BackendTLS) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Backend
func (this *Backend) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Backend
func (this *Backend) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RequestRedirect
func (this *RequestRedirect) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RequestRedirect
func (this *RequestRedirect) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderNameValue
func (this *HeaderNameValue) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderNameValue
func (this *HeaderNameValue) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RequestHeaderModifier
func (this *RequestHeaderModifier) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RequestHeaderModifier
func (this *RequestHeaderModifier) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RouteMatch
func (this *RouteMatch) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RouteMatch
func (this *RouteMatch) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Route
func (this *Route) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Route
func (this *Route) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Resource
func (this *Resource) MarshalJSON() ([]byte, error) {
	str, err := GwxdsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Resource
func (this *Resource) UnmarshalJSON(b []byte) error {
	return GwxdsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	GwxdsMarshaler   = &jsonpb.Marshaler{}
	GwxdsUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
